/**
 * FRAMELIMIT.COM — Laptop Data
 * Single source of truth for all laptop specs, scores, and affiliate links.
 * tag: framelimit20-20
 *
 * TIERS:   high-end | mid-range | budget
 * UPDATED: March 2026
 *
 * HOW TO USE ON ANY PAGE:
 *   <script src="laptops.js"></script>
 *   Then access window.LAPTOPS, window.LAPTOPS_BY_TIER, window.getLaptop(id)
 */

const LAPTOPS = [

  /* ============================================================
     🔥 HIGH-END — RTX 5080 / 5090
     ============================================================ */
  {
    id: 'msi-titan-18-hx-ai',
    brand: 'MSI',
    name: 'Titan 18 HX AI',
    shortName: 'MSI Titan 18 HX AI',
    tier: 'high-end',
    badge: 'Desktop Replacement King',
    gpu: 'RTX 5090',
    gpuVram: '24GB GDDR7',
    tgp: 175,           // Watts
    cpu: 'Intel Core Ultra 9 285HX',
    ram: '64GB DDR5-5600',
    ramUpgradeable: true,
    storage: '2TB PCIe Gen5 NVMe',
    display: {
      size: 18,
      res: '3840×2400',
      hz: 120,
      panel: 'Mini-LED',
      nits: 1600,
      hdr: 'HDR1000',
    },
    weight: 3.3,        // kg
    battery: 99,        // Wh
    price: 4499,        // USD MSRP
    score: 9.6,
    scores: { perf: 9.9, display: 9.7, thermals: 8.2, battery: 6.0, build: 9.5, value: 7.8 },
    bestFor: 'No-compromise desktop replacement, 4K gaming',
    avoidIf: 'You need to carry it anywhere',
    amazonUrl: 'https://www.amazon.com/s?k=MSI+Titan+18+HX+AI+RTX+5090&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/msi_titan_18_hx_ai_1.webp',
    imgBg: '#0a0a0a',
    tags: ['desktop-replacement', 'nvidia', '4k', 'flagship'],
  },

  {
    id: 'msi-raider-18-hx-ai',
    brand: 'MSI',
    name: 'Raider 18 HX AI',
    shortName: 'MSI Raider 18 HX AI',
    tier: 'high-end',
    badge: 'Best All-Round 18"',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 285HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '2TB PCIe Gen5 NVMe',
    display: {
      size: 18,
      res: '2560×1600',
      hz: 240,
      panel: 'IPS',
      nits: 500,
      hdr: 'HDR400',
    },
    weight: 3.1,
    battery: 99,
    price: 3299,
    score: 9.3,
    scores: { perf: 9.5, display: 8.8, thermals: 8.6, battery: 6.5, build: 9.3, value: 8.5 },
    bestFor: 'High-refresh 1440p/4K, upgradeable powerhouse',
    avoidIf: 'You want OLED or portability',
    amazonUrl: 'https://www.amazon.com/s?k=MSI+Raider+18+HX+AI+RTX+5080&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/msi_raider_18_hx_ai_1.webp',
    imgBg: '#0a0a0a',
    tags: ['desktop-replacement', 'nvidia', 'high-refresh', 'flagship'],
  },

  {
    id: 'asus-rog-scar-18-2026',
    brand: 'ASUS ROG',
    name: 'Strix SCAR 18 (2026)',
    shortName: 'ROG Strix SCAR 18',
    tier: 'high-end',
    badge: 'Best Cooling in Class',
    gpu: 'RTX 5090',
    gpuVram: '24GB GDDR7',
    tgp: 175,
    cpu: 'AMD Ryzen AI 9 HX 370',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '2TB PCIe Gen4 NVMe',
    display: {
      size: 18,
      res: '2560×1600',
      hz: 240,
      panel: 'IPS',
      nits: 500,
      hdr: 'HDR400',
    },
    weight: 3.1,
    battery: 90,
    price: 3999,
    score: 9.5,
    scores: { perf: 9.8, display: 9.0, thermals: 9.5, battery: 6.8, build: 9.6, value: 8.2 },
    bestFor: 'Sustained max performance, competitive gaming',
    avoidIf: 'Battery life or portability matter',
    amazonUrl: 'https://www.amazon.com/s?k=ASUS+ROG+Strix+SCAR+18+2026+RTX+5090&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/asus_rog_strix_scar_18_1.webp',
    imgBg: '#0d0d14',
    tags: ['desktop-replacement', 'nvidia', 'amd-cpu', 'cooling-king', 'flagship'],
  },

  {
    id: 'asus-rog-scar-16-2026',
    brand: 'ASUS ROG',
    name: 'Strix SCAR 16 (2026)',
    shortName: 'ROG Strix SCAR 16',
    tier: 'high-end',
    badge: 'Best 16" Performance',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 175,
    cpu: 'AMD Ryzen AI 9 HX 370',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'IPS',
      nits: 500,
      hdr: 'HDR400',
    },
    weight: 2.7,
    battery: 90,
    price: 2999,
    score: 9.4,
    scores: { perf: 9.6, display: 9.0, thermals: 9.3, battery: 7.2, build: 9.5, value: 8.6 },
    bestFor: 'Portable flagship, competitive esports + AAA',
    avoidIf: 'You need OLED or prefer Intel',
    amazonUrl: 'https://www.amazon.com/s?k=ASUS+ROG+Strix+SCAR+16+2026+RTX+5080&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/asus_rog_strix_scar_16_1.webp',
    imgBg: '#0d0d14',
    tags: ['16-inch', 'nvidia', 'amd-cpu', 'cooling-king', 'flagship'],
  },

  {
    id: 'lenovo-legion-pro-7i-gen10',
    brand: 'Lenovo',
    name: 'Legion Pro 7i Gen 10',
    shortName: 'Legion Pro 7i Gen 10',
    tier: 'high-end',
    badge: 'Best Value Flagship',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 285HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'IPS',
      nits: 500,
      hdr: 'HDR400',
    },
    weight: 2.8,
    battery: 99,
    price: 2699,
    score: 9.4,
    scores: { perf: 9.5, display: 9.0, thermals: 9.0, battery: 7.5, build: 9.2, value: 9.2 },
    bestFor: 'Max performance at the best price-per-frame',
    avoidIf: 'You want OLED display or AMD CPU',
    amazonUrl: 'https://www.amazon.com/s?k=Lenovo+Legion+Pro+7i+Gen+10+RTX+5080&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/lenovo_legion_pro_7i_gen_10_1.webp',
    imgBg: '#070d12',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'flagship', 'best-value-flagship'],
  },

  {
    id: 'alienware-18-area-51',
    brand: 'Alienware',
    name: '18 Area-51',
    shortName: 'Alienware 18 Area-51',
    tier: 'high-end',
    badge: 'Most Powerful Laptop Ever Made',
    gpu: 'RTX 5090',
    gpuVram: '24GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 285HX',
    ram: '64GB DDR5-5600',
    ramUpgradeable: true,
    storage: '4TB PCIe Gen5 NVMe (RAID)',
    display: {
      size: 18,
      res: '2560×1600',
      hz: 480,
      panel: 'IPS',
      nits: 500,
      hdr: 'HDR400',
    },
    weight: 4.2,
    battery: 99,
    price: 4999,
    score: 9.2,
    scores: { perf: 9.9, display: 9.2, thermals: 8.5, battery: 5.5, build: 9.8, value: 7.0 },
    bestFor: 'Absolute maximum performance, Alienware ecosystem',
    avoidIf: 'Budget exists, weight/portability matter at all',
    amazonUrl: 'https://www.amazon.com/s?k=Alienware+18+Area-51+RTX+5090&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/alienware_18_area-51_1.webp',
    imgBg: '#07070f',
    tags: ['desktop-replacement', 'nvidia', 'flagship', '480hz'],
  },

  {
    id: 'razer-blade-16-oled-2026',
    brand: 'Razer',
    name: 'Blade 16 (2026)',
    shortName: 'Razer Blade 16 OLED',
    tier: 'high-end',
    badge: 'Best OLED Gaming Laptop',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 150,           // thin chassis constraint
    cpu: 'Intel Core Ultra 9 285H',
    ram: '32GB LPDDR5X',
    ramUpgradeable: false,
    storage: '2TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'OLED',
      nits: 1000,
      hdr: 'HDR True Black 600',
    },
    weight: 2.1,
    battery: 95.2,
    price: 3299,
    score: 9.3,
    scores: { perf: 9.0, display: 9.9, thermals: 8.0, battery: 7.8, build: 9.9, value: 8.0 },
    bestFor: 'Premium build + OLED display, creator-gamers',
    avoidIf: 'You want maximum TGP or user-upgradeable RAM',
    amazonUrl: 'https://www.amazon.com/s?k=Razer+Blade+16+2026+RTX+5080+OLED&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/razer_blade_16_oled_1.webp',
    imgBg: '#060606',
    tags: ['16-inch', 'nvidia', 'oled', 'thin', 'flagship', 'premium-build'],
  },

  {
    id: 'razer-blade-18-2026',
    brand: 'Razer',
    name: 'Blade 18 (2026)',
    shortName: 'Razer Blade 18',
    tier: 'high-end',
    badge: 'Best Premium 18"',
    gpu: 'RTX 5090',
    gpuVram: '24GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 285HX',
    ram: '64GB DDR5-5600',
    ramUpgradeable: true,
    storage: '2TB PCIe Gen4 NVMe',
    display: {
      size: 18,
      res: '2560×1600',
      hz: 300,
      panel: 'IPS',
      nits: 500,
      hdr: 'HDR400',
    },
    weight: 3.2,
    battery: 99,
    price: 4499,
    score: 9.1,
    scores: { perf: 9.7, display: 9.0, thermals: 8.4, battery: 6.2, build: 9.9, value: 7.5 },
    bestFor: 'Razer loyalists, premium large-screen experience',
    avoidIf: 'Better value exists at same price elsewhere',
    amazonUrl: 'https://www.amazon.com/s?k=Razer+Blade+18+2026+RTX+5090&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/razer_blade_18_1.webp',
    imgBg: '#060606',
    tags: ['desktop-replacement', 'nvidia', 'flagship', 'premium-build'],
  },

  {
    id: 'hp-omen-max-16-2026',
    brand: 'HP',
    name: 'Omen Max 16 (2026)',
    shortName: 'HP Omen Max 16',
    tier: 'high-end',
    badge: 'Best Underrated Flagship',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 285HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '2TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'IPS',
      nits: 500,
      hdr: 'HDR400',
    },
    weight: 2.9,
    battery: 99,
    price: 2499,
    score: 9.1,
    scores: { perf: 9.4, display: 8.8, thermals: 8.8, battery: 7.6, build: 9.0, value: 9.3 },
    bestFor: 'Full 175W flagship performance at mid-range money',
    avoidIf: 'Brand prestige or OLED matters to you',
    amazonUrl: 'https://www.amazon.com/s?k=HP+Omen+Max+16+RTX+5080+2026&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/hp_omen_max_16_1.webp',
    imgBg: '#0a0a0a',
    tags: ['16-inch', 'nvidia', 'flagship', 'best-value-flagship'],
  },

  {
    id: 'asus-rog-zephyrus-g16-high',
    brand: 'ASUS ROG',
    name: 'Zephyrus G16 (RTX 5080/5090)',
    shortName: 'Zephyrus G16 High-End',
    tier: 'high-end',
    badge: 'Thinnest Flagship',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 150,
    cpu: 'Intel Core Ultra 9 285H',
    ram: '32GB LPDDR5X',
    ramUpgradeable: false,
    storage: '2TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'OLED',
      nits: 1100,
      hdr: 'HDR True Black 600',
    },
    weight: 1.85,
    battery: 90,
    price: 2999,
    score: 9.2,
    scores: { perf: 9.1, display: 9.8, thermals: 8.5, battery: 8.2, build: 9.6, value: 8.4 },
    bestFor: 'Portable flagship, best OLED + performance balance',
    avoidIf: 'You need full 175W TGP or upgradeable RAM',
    amazonUrl: 'https://www.amazon.com/dp/B0FLM687GK?tag=framelimit20-20',
    amazonAsin: 'B0FLM687GK',
    imgUrl: 'images/laptops/laptops/asus_rog_zephyrus_g16_high-end_1.webp',
    imgBg: '#080d12',
    tags: ['16-inch', 'nvidia', 'oled', 'thin', 'flagship'],
  },

  /* ============================================================
     ⚖️ MID-RANGE — RTX 5070 / 5070 Ti  (YOUR MONEY MAKERS)
     ============================================================ */
  {
    id: 'lenovo-legion-5i-gen10',
    brand: 'Lenovo',
    name: 'Legion 5i Gen 10',
    shortName: 'Lenovo Legion 5i',
    tier: 'mid-range',
    badge: '#1 Mid-Range Pick',
    gpu: 'RTX 5070 Ti',
    gpuVram: '12GB GDDR7',
    tgp: 140,
    cpu: 'Intel Core Ultra 7 265HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 165,
      panel: 'IPS',
      nits: 400,
      hdr: false,
    },
    weight: 2.5,
    battery: 80,
    price: 1799,
    score: 9.2,
    scores: { perf: 9.1, display: 8.5, thermals: 9.0, battery: 7.8, build: 8.8, value: 9.5 },
    bestFor: 'Best price-per-frame in 2026, 1440p gaming',
    avoidIf: 'You want OLED or thin chassis',
    amazonUrl: 'https://www.amazon.com/s?k=Lenovo+Legion+5i+Gen+10+RTX+5070+Ti&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/lenovo_legion_5i_1.webp',
    imgBg: '#070d12',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'best-value', 'mid-range'],
  },

  {
    id: 'lenovo-legion-5-gen10-amd',
    brand: 'Lenovo',
    name: 'Legion 5 Gen 10 (AMD)',
    shortName: 'Lenovo Legion 5 AMD',
    tier: 'mid-range',
    badge: 'Best AMD Mid-Range',
    gpu: 'RTX 5070',
    gpuVram: '12GB GDDR7',
    tgp: 130,
    cpu: 'AMD Ryzen AI 7 370',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 165,
      panel: 'IPS',
      nits: 400,
      hdr: false,
    },
    weight: 2.4,
    battery: 80,
    price: 1499,
    score: 8.9,
    scores: { perf: 8.7, display: 8.2, thermals: 9.0, battery: 8.2, build: 8.8, value: 9.4 },
    bestFor: 'AMD fans, best battery + performance balance under $1,500',
    avoidIf: 'You want 1440p display or higher TGP',
    amazonUrl: 'https://www.amazon.com/s?k=Lenovo+Legion+5+Gen+10+AMD+RTX+5070&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/lenovo_legion_5_amd_1.webp',
    imgBg: '#070d12',
    tags: ['16-inch', 'nvidia', 'amd-cpu', 'best-value', 'mid-range'],
  },

  {
    id: 'asus-rog-zephyrus-g14-2026',
    brand: 'ASUS ROG',
    name: 'Zephyrus G14 (2026)',
    shortName: 'Zephyrus G14',
    tier: 'mid-range',
    badge: 'Best Compact Powerhouse',
    gpu: 'RTX 5070',
    gpuVram: '12GB GDDR7',
    tgp: 100,
    cpu: 'AMD Ryzen AI 9 365',
    ram: '32GB LPDDR5X',
    ramUpgradeable: false,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 14,
      res: '2880×1800',
      hz: 120,
      panel: 'OLED',
      nits: 1100,
      hdr: 'HDR True Black 600',
    },
    weight: 1.65,
    battery: 73,
    price: 1799,
    score: 9.0,
    scores: { perf: 8.6, display: 9.8, thermals: 8.2, battery: 8.6, build: 9.5, value: 8.8 },
    bestFor: 'Ultraportable + OLED, travel-friendly gamer',
    avoidIf: 'You need max FPS or upgradeable RAM',
    amazonUrl: 'https://www.amazon.com/s?k=ASUS+ROG+Zephyrus+G14+2026+RTX+5070&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/asus_rog_zephyrus_g14_1.webp',
    imgBg: '#0d0d14',
    tags: ['14-inch', 'nvidia', 'amd-cpu', 'oled', 'thin', 'mid-range'],
  },

  {
    id: 'asus-rog-zephyrus-g16-mid',
    brand: 'ASUS ROG',
    name: 'Zephyrus G16 (RTX 5070)',
    shortName: 'Zephyrus G16 Mid',
    tier: 'mid-range',
    badge: 'Best OLED Under $2K',
    gpu: 'RTX 5070 Ti',
    gpuVram: '12GB GDDR7',
    tgp: 120,
    cpu: 'Intel Core Ultra 7 265H',
    ram: '32GB LPDDR5X',
    ramUpgradeable: false,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'OLED',
      nits: 1100,
      hdr: 'HDR True Black 600',
    },
    weight: 1.85,
    battery: 90,
    price: 1999,
    score: 8.9,
    scores: { perf: 8.8, display: 9.8, thermals: 8.3, battery: 8.0, build: 9.6, value: 8.6 },
    bestFor: 'OLED quality + portability at mid-range money',
    avoidIf: 'Max TGP or upgradeable RAM is required',
    amazonUrl: 'https://www.amazon.com/s?k=ASUS+ROG+Zephyrus+G16+RTX+5070+Ti&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/asus_rog_zephyrus_g16_mid-range_1.webp',
    imgBg: '#080d12',
    tags: ['16-inch', 'nvidia', 'oled', 'thin', 'mid-range'],
  },

  {
    id: 'acer-predator-helios-neo-16-2025',
    brand: 'Acer',
    name: 'Predator Helios Neo 16 (2025)',
    shortName: 'Predator Helios Neo 16',
    tier: 'mid-range',
    badge: 'Best Budget Mid-Range',
    gpu: 'RTX 5070',
    gpuVram: '12GB GDDR7',
    tgp: 130,
    cpu: 'Intel Core Ultra 7 265HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 165,
      panel: 'IPS',
      nits: 400,
      hdr: false,
    },
    weight: 2.6,
    battery: 76,
    price: 1499,
    score: 8.7,
    scores: { perf: 8.8, display: 8.4, thermals: 8.6, battery: 7.4, build: 8.5, value: 9.3 },
    bestFor: 'High-performance gaming on a strict budget',
    avoidIf: 'Build quality or display premium matters',
    amazonUrl: 'https://www.amazon.com/s?k=Acer+Predator+Helios+Neo+16+RTX+5070&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/acer_predator_helios_neo_16_1.webp',
    imgBg: '#05100a',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'mid-range', 'best-value'],
  },

  {
    id: 'hp-omen-16-rtx5070-2026',
    brand: 'HP',
    name: 'Omen 16 (RTX 5070)',
    shortName: 'HP Omen 16',
    tier: 'mid-range',
    badge: 'Best HP Under $1,500',
    gpu: 'RTX 5070',
    gpuVram: '12GB GDDR7',
    tgp: 130,
    cpu: 'Intel Core Ultra 7 265H',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '1920×1080',
      hz: 144,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.4,
    battery: 83,
    price: 1399,
    score: 8.5,
    scores: { perf: 8.6, display: 7.8, thermals: 8.4, battery: 8.0, build: 8.6, value: 9.0 },
    bestFor: 'Solid all-rounder with good upgradeability',
    avoidIf: '1440p or high-nit display is important to you',
    amazonUrl: 'https://www.amazon.com/s?k=HP+Omen+16+RTX+5070+2026&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/hp_omen_16_rtx_5070_1.webp',
    imgBg: '#0a0a0a',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'mid-range'],
  },

  {
    id: 'asus-tuf-gaming-f16-rtx5070',
    brand: 'ASUS TUF',
    name: 'Gaming F16 (RTX 5070)',
    shortName: 'TUF Gaming F16',
    tier: 'mid-range',
    badge: 'Best Mid-Range Build Quality',
    gpu: 'RTX 5070',
    gpuVram: '12GB GDDR7',
    tgp: 115,
    cpu: 'Intel Core Ultra 7 265H',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 165,
      panel: 'IPS',
      nits: 400,
      hdr: false,
    },
    weight: 2.2,
    battery: 90,
    price: 1299,
    score: 8.6,
    scores: { perf: 8.5, display: 8.3, thermals: 8.8, battery: 8.4, build: 9.2, value: 9.2 },
    bestFor: 'MIL-SPEC durability, great battery, under $1,300',
    avoidIf: 'You need maximum GPU TGP',
    amazonUrl: 'https://www.amazon.com/s?k=ASUS+TUF+Gaming+F16+RTX+5070+2026&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/asus_tuf_gaming_f16_1.webp',
    imgBg: '#0a0d0a',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'mid-range', 'best-value'],
  },

  {
    id: 'asus-tuf-gaming-a16-amd',
    brand: 'ASUS TUF',
    name: 'Gaming A16 (AMD Advantage)',
    shortName: 'TUF Gaming A16 AMD',
    tier: 'mid-range',
    badge: 'Best AMD Advantage Build',
    gpu: 'Radeon RX 7700S',
    gpuVram: '8GB GDDR6',
    tgp: 100,
    cpu: 'AMD Ryzen AI 7 360',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 165,
      panel: 'IPS',
      nits: 400,
      hdr: false,
    },
    weight: 2.2,
    battery: 90,
    price: 1099,
    score: 8.3,
    scores: { perf: 7.8, display: 8.3, thermals: 9.0, battery: 9.0, build: 9.2, value: 9.4 },
    bestFor: 'AMD loyalists, longest battery, best build under $1,100',
    avoidIf: 'You want Nvidia DLSS 4 or max rasterization perf',
    amazonUrl: 'https://www.amazon.com/s?k=ASUS+TUF+Gaming+A16+AMD+Advantage+2026&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/asus_tuf_gaming_a16_amd_advantage_1.webp',
    imgBg: '#0a0d0a',
    tags: ['16-inch', 'amd-gpu', 'amd-cpu', 'mid-range'],
  },

  {
    id: 'msi-vector-16-hx-ai',
    brand: 'MSI',
    name: 'Vector 16 HX AI',
    shortName: 'MSI Vector 16 HX AI',
    tier: 'mid-range',
    badge: 'Best MSI Mid-Range',
    gpu: 'RTX 5070 Ti',
    gpuVram: '12GB GDDR7',
    tgp: 140,
    cpu: 'Intel Core Ultra 7 265HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'IPS',
      nits: 500,
      hdr: 'HDR400',
    },
    weight: 2.6,
    battery: 99,
    price: 1999,
    score: 8.8,
    scores: { perf: 9.0, display: 8.8, thermals: 8.7, battery: 7.6, build: 8.9, value: 8.9 },
    bestFor: 'Near-flagship performance at mid-range price',
    avoidIf: 'OLED display or thin chassis is a priority',
    amazonUrl: 'https://www.amazon.com/s?k=MSI+Vector+16+HX+AI+RTX+5070+Ti&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/msi_vector_16_hx_ai_1.webp',
    imgBg: '#0d0d0d',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'mid-range'],
  },

  {
    id: 'dell-alienware-16x-aurora',
    brand: 'Alienware',
    name: '16X Aurora (RTX 5070 Ti)',
    shortName: 'Alienware 16X Aurora',
    tier: 'mid-range',
    badge: 'Best Alienware Mid-Range',
    gpu: 'RTX 5070 Ti',
    gpuVram: '12GB GDDR7',
    tgp: 140,
    cpu: 'AMD Ryzen AI 9 HX 370',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 165,
      panel: 'IPS',
      nits: 400,
      hdr: false,
    },
    weight: 2.9,
    battery: 90,
    price: 2299,
    score: 8.7,
    scores: { perf: 9.0, display: 8.5, thermals: 8.8, battery: 7.2, build: 9.4, value: 8.4 },
    bestFor: 'Alienware build quality at a non-Alienware price',
    avoidIf: 'Better value exists from Legion/SCAR at same price',
    amazonUrl: 'https://www.amazon.com/s?k=Alienware+16X+Aurora+RTX+5070+Ti&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/alienware_16x_aurora_1.webp',
    imgBg: '#07070f',
    tags: ['16-inch', 'nvidia', 'amd-cpu', 'mid-range'],
  },

  /* ============================================================
     💰 BUDGET — RTX 5050 / 5060 (NEW GEN ONLY)
     ============================================================ */
  {
    id: 'lenovo-loq-15-gen10',
    brand: 'Lenovo',
    name: 'LOQ 15 Gen 10 (RTX 5060)',
    shortName: 'Lenovo LOQ 15',
    tier: 'budget',
    badge: '#1 Budget Pick',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 100,
    cpu: 'Intel Core Ultra 5 245H',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 15.6,
      res: '1920×1080',
      hz: 144,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.4,
    battery: 60,
    price: 999,
    score: 8.5,
    scores: { perf: 8.0, display: 7.8, thermals: 8.6, battery: 7.2, build: 8.4, value: 9.6 },
    bestFor: 'Best RTX 5060 under $1,000, 1080p gaming',
    avoidIf: '1440p or OLED is something you care about',
    amazonUrl: 'https://www.amazon.com/s?k=Lenovo+LOQ+15+Gen+10+RTX+5060&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/lenovo_loq_15_gen_10_1.webp',
    imgBg: '#070d12',
    tags: ['15-inch', 'nvidia', 'intel-cpu', 'budget', 'best-value'],
  },

  {
    id: 'lenovo-loq-16-gen10',
    brand: 'Lenovo',
    name: 'LOQ 16 Gen 10',
    shortName: 'Lenovo LOQ 16',
    tier: 'budget',
    badge: 'Best 16" Budget',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 100,
    cpu: 'Intel Core Ultra 5 245H',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 144,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.5,
    battery: 60,
    price: 1049,
    score: 8.4,
    scores: { perf: 8.0, display: 8.0, thermals: 8.6, battery: 7.0, build: 8.4, value: 9.4 },
    bestFor: 'Bigger screen budget gaming, good keyboard',
    avoidIf: 'Battery life is critical',
    amazonUrl: 'https://www.amazon.com/s?k=Lenovo+LOQ+16+Gen+10+RTX+5060&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/lenovo_loq_16_1.webp',
    imgBg: '#070d12',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'budget'],
  },

  {
    id: 'acer-nitro-16-2025',
    brand: 'Acer',
    name: 'Nitro 16 (2025)',
    shortName: 'Acer Nitro 16',
    tier: 'budget',
    badge: 'Best Acer Budget Pick',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 100,
    cpu: 'AMD Ryzen 7 8745H',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 165,
      panel: 'IPS',
      nits: 350,
      hdr: false,
    },
    weight: 2.5,
    battery: 76,
    price: 1099,
    score: 8.3,
    scores: { perf: 7.9, display: 8.5, thermals: 8.2, battery: 7.6, build: 8.2, value: 9.2 },
    bestFor: 'Budget 1440p gaming, good display for price',
    avoidIf: 'You want a premium chassis feel',
    amazonUrl: 'https://www.amazon.com/s?k=Acer+Nitro+16+2025+RTX+5060&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/acer_nitro_16_1.webp',
    imgBg: '#05100a',
    tags: ['16-inch', 'nvidia', 'amd-cpu', 'budget', '1440p'],
  },

  {
    id: 'acer-nitro-v-16',
    brand: 'Acer',
    name: 'Nitro V 16 (2025)',
    shortName: 'Acer Nitro V 16',
    tier: 'budget',
    badge: 'Best Under $900',
    gpu: 'RTX 5050',
    gpuVram: '6GB GDDR7',
    tgp: 80,
    cpu: 'AMD Ryzen 5 8645H',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 144,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.4,
    battery: 65,
    price: 849,
    score: 8.0,
    scores: { perf: 7.5, display: 7.8, thermals: 8.4, battery: 7.8, build: 8.0, value: 9.5 },
    bestFor: 'Absolute entry point to RTX 50 series gaming',
    avoidIf: 'You play demanding AAA titles at high settings',
    amazonUrl: 'https://www.amazon.com/s?k=Acer+Nitro+V+16+2025+RTX+5050&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/acer_nitro_v_16_1.webp',
    imgBg: '#05100a',
    tags: ['16-inch', 'nvidia', 'amd-cpu', 'budget'],
  },

  {
    id: 'hp-victus-16-rtx5060',
    brand: 'HP',
    name: 'Victus 16 (RTX 5060)',
    shortName: 'HP Victus 16',
    tier: 'budget',
    badge: 'Best HP Budget Laptop',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 95,
    cpu: 'AMD Ryzen 7 8745H',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 16.1,
      res: '1920×1080',
      hz: 144,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.3,
    battery: 70,
    price: 999,
    score: 8.2,
    scores: { perf: 7.9, display: 7.7, thermals: 8.2, battery: 7.8, build: 8.3, value: 9.3 },
    bestFor: 'HP fans, clean design, solid budget option',
    avoidIf: '1440p display matters, or you want more TGP',
    amazonUrl: 'https://www.amazon.com/s?k=HP+Victus+16+RTX+5060+2025&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/hp_victus_16_1.webp',
    imgBg: '#0a0a0a',
    tags: ['16-inch', 'nvidia', 'amd-cpu', 'budget'],
  },

  {
    id: 'asus-tuf-a15-rtx5060',
    brand: 'ASUS TUF',
    name: 'Gaming A15 (RTX 5060)',
    shortName: 'TUF Gaming A15',
    tier: 'budget',
    badge: 'Best Battery in Budget',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 95,
    cpu: 'AMD Ryzen 7 8745H',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 15.6,
      res: '1920×1080',
      hz: 144,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.2,
    battery: 90,
    price: 1049,
    score: 8.3,
    scores: { perf: 7.9, display: 7.8, thermals: 8.8, battery: 9.0, build: 9.0, value: 9.2 },
    bestFor: 'MIL-SPEC budget laptop, best-in-class battery life',
    avoidIf: '1440p or above 1080p display matters',
    amazonUrl: 'https://www.amazon.com/s?k=ASUS+TUF+Gaming+A15+RTX+5060+2026&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/asus_tuf_a15_1.webp',
    imgBg: '#0a0d0a',
    tags: ['15-inch', 'nvidia', 'amd-cpu', 'budget', 'battery-life'],
  },

  {
    id: 'asus-tuf-a16-entry',
    brand: 'ASUS TUF',
    name: 'Gaming A16 (Entry Config)',
    shortName: 'TUF Gaming A16 Entry',
    tier: 'budget',
    badge: 'Best Build Quality Under $1,200',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 100,
    cpu: 'AMD Ryzen AI 7 360',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 165,
      panel: 'IPS',
      nits: 400,
      hdr: false,
    },
    weight: 2.2,
    battery: 90,
    price: 1149,
    score: 8.4,
    scores: { perf: 8.0, display: 8.2, thermals: 8.8, battery: 8.8, build: 9.2, value: 9.0 },
    bestFor: 'Best budget build quality, great thermals',
    avoidIf: 'You want RTX 5070+ performance',
    amazonUrl: 'https://www.amazon.com/s?k=ASUS+TUF+Gaming+A16+RTX+5060+2026&tag=framelimit20-20',
    amazonAsin: 'B0G3QSC6H4',
    imgUrl: 'images/laptops/laptops/asus_tuf_a16_entry_config_1.webp',
    imgBg: '#0a0d0a',
    tags: ['16-inch', 'nvidia', 'amd-cpu', 'budget'],
  },

  {
    id: 'msi-katana-15-hx',
    brand: 'MSI',
    name: 'Katana 15 HX (RTX 5060)',
    shortName: 'MSI Katana 15 HX',
    tier: 'budget',
    badge: 'Best MSI Budget Pick',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 100,
    cpu: 'Intel Core i7-14700HX',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 15.6,
      res: '1920×1080',
      hz: 144,
      panel: 'IPS',
      nits: 250,
      hdr: false,
    },
    weight: 2.25,
    battery: 53,
    price: 949,
    score: 7.9,
    scores: { perf: 7.8, display: 7.4, thermals: 8.0, battery: 6.8, build: 8.2, value: 9.0 },
    bestFor: 'Sub-$1,000 MSI, proven HX platform',
    avoidIf: 'Battery life or display quality matters',
    amazonUrl: 'https://www.amazon.com/s?k=MSI+Katana+15+HX+RTX+5060&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/msi_katana_15_hx_1.webp',
    imgBg: '#0a0a0a',
    tags: ['15-inch', 'nvidia', 'intel-cpu', 'budget'],
  },

  {
    id: 'gigabyte-g6-rtx5060',
    brand: 'Gigabyte',
    name: 'G6 (RTX 5060)',
    shortName: 'Gigabyte G6',
    tier: 'budget',
    badge: 'Best Hidden Gem',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 100,
    cpu: 'Intel Core i7-13620H',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 165,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.3,
    battery: 54,
    price: 899,
    score: 7.8,
    scores: { perf: 7.8, display: 7.9, thermals: 8.0, battery: 6.5, build: 7.8, value: 9.2 },
    bestFor: 'Underrated budget pick, good display ratio',
    avoidIf: 'Battery life is non-negotiable',
    amazonUrl: 'https://www.amazon.com/s?k=Gigabyte+G6+RTX+5060+2026&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/gigabyte_g6_g5_1.webp',
    imgBg: '#0d1117',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'budget'],
  },

  {
    id: 'dell-g15-rtx5060',
    brand: 'Dell',
    name: 'G15 (RTX 5060)',
    shortName: 'Dell G15',
    tier: 'budget',
    badge: 'Best Dell Budget Laptop',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 100,
    cpu: 'Intel Core i7-14650HX',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 15.6,
      res: '1920×1080',
      hz: 165,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.6,
    battery: 54,
    price: 999,
    score: 8.0,
    scores: { perf: 7.8, display: 7.8, thermals: 8.2, battery: 6.6, build: 8.4, value: 9.0 },
    bestFor: 'Dell reliability, good upgradeability',
    avoidIf: 'Battery or portability is important',
    amazonUrl: 'https://www.amazon.com/s?k=Dell+G15+RTX+5060+2026&tag=framelimit20-20',
    amazonAsin: null,
    imgUrl: 'images/laptops/laptops/dell_g15_1.webp',
    imgBg: '#0d1117',
    tags: ['15-inch', 'nvidia', 'intel-cpu', 'budget'],
  },

];

/* ──────────────────────────────────────────────
   HELPER FUNCTIONS  (available as globals)
   ────────────────────────────────────────────── */

/** Get a laptop by its id string */
function getLaptop(id) {
  return LAPTOPS.find(l => l.id === id) || null;
}

/** Group laptops by tier */
const LAPTOPS_BY_TIER = {
  'high-end':  LAPTOPS.filter(l => l.tier === 'high-end'),
  'mid-range': LAPTOPS.filter(l => l.tier === 'mid-range'),
  'budget':    LAPTOPS.filter(l => l.tier === 'budget'),
};

/** Filter by tag(s) */
function getLaptopsByTag(...tags) {
  return LAPTOPS.filter(l => tags.every(t => l.tags.includes(t)));
}

/** Sort helpers */
const sortByScore    = arr => [...arr].sort((a, b) => b.score - a.score);
const sortByPrice    = arr => [...arr].sort((a, b) => a.price - b.price);
const sortByTGP      = arr => [...arr].sort((a, b) => b.tgp - a.tgp);

/* Expose everything globally for plain HTML pages */
window.LAPTOPS         = LAPTOPS;
window.LAPTOPS_BY_TIER = LAPTOPS_BY_TIER;
window.getLaptop       = getLaptop;
window.getLaptopsByTag = getLaptopsByTag;
window.sortByScore     = sortByScore;
window.sortByPrice     = sortByPrice;
window.sortByTGP       = sortByTGP;
