/**
 * FRAMELIMIT.COM — Laptop Data
 * Single source of truth for all laptop specs, scores, and affiliate links.
 * tag: framelimit20-20
 *
 * TIERS:   high-end | mid-range | budget
 * UPDATED: July 2026
 * Prices are editorial reference/MSRP or last-observed values, not live prices.
 * Always use Amazon/retailer pages for the current checkout price.
 *
 * HOW TO USE ON ANY PAGE:
 *   <script src="laptops.js"></script>
 *   Then access window.LAPTOPS, window.LAPTOPS_BY_TIER, window.getLaptop(id)
 */

const FL_DATA_LAST_CHECKED = '2026-07-15';
const FL_DATA_LAST_CHECKED_LABEL = 'Direct retail links audited Jul 15, 2026';

const LAPTOP_CATALOG = [

  /* ============================================================
     🔥 HIGH-END — RTX 5080 / 5090
     ============================================================ */
  {
    id: 'msi-titan-18-hx-ai',
    brand: 'MSI',
    name: 'Titan 18 HX AI',
    shortName: 'MSI Titan 18 HX AI',
    tier: 'high-end',
    badge: 'Desktop Replacement King',
    gpu: 'RTX 5090',
    gpuVram: '24GB GDDR7',
    tgp: 175,           // Watts
    cpu: 'Intel Core Ultra 9 285HX',
    ram: '64GB DDR5-5600',
    ramUpgradeable: true,
    storage: '6TB NVMe (Amazon configuration)',
    display: {
      size: 18,
      res: '3840×2400',
      hz: 120,
      panel: 'Mini-LED',
      nits: 1600,
      hdr: 'HDR1000',
    },
    weight: 3.3,        // kg
    battery: 99,        // Wh
    price: null,        // No featured Amazon offer during Jul 12 audit
    score: 9.6,
    scores: { perf: 9.9, display: 9.7, thermals: 8.2, battery: 6.0, build: 9.5, value: 7.8 },
    bestFor: 'No-compromise desktop replacement, 4K gaming',
    avoidIf: 'You need to carry it anywhere',
    amazonUrl: 'https://www.amazon.com/dp/B0F1DWFQTX/?tag=framelimit20-20',
    amazonAsin: 'B0F1DWFQTX',
    imgUrl: 'images/laptops/msi-titan-18-hx-ai.webp',
    imgBg: '#0a0a0a',
    tags: ['desktop-replacement', 'nvidia', '4k', 'flagship'],
  },

  {
    id: 'msi-raider-18-hx-ai',
    brand: 'MSI',
    name: 'Raider 18 HX AI',
    shortName: 'MSI Raider 18 HX AI',
    tier: 'high-end',
    badge: 'Best All-Round 18"',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 285HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '2TB PCIe Gen5 NVMe',
    display: {
      size: 18,
      res: '2560×1600',
      hz: 240,
      panel: 'IPS',
      nits: 500,
      hdr: 'HDR400',
    },
    weight: 3.1,
    battery: 99,
    price: 3543,
    score: 9.3,
    scores: { perf: 9.5, display: 8.8, thermals: 8.6, battery: 6.5, build: 9.3, value: 8.5 },
    bestFor: 'High-refresh 1440p/4K, upgradeable powerhouse',
    avoidIf: 'You want OLED or portability',
    amazonUrl: 'https://www.amazon.com/dp/B0F4PHGLW3?tag=framelimit20-20',
    amazonAsin: 'B0F4PHGLW3',
    imgUrl: 'images/laptops/msi-raider-18-hx-ai.webp',
    imgBg: '#0a0a0a',
    tags: ['desktop-replacement', 'nvidia', 'high-refresh', 'flagship'],
  },

  {
    id: 'asus-rog-scar-18-2026',
    brand: 'ASUS ROG',
    name: 'Strix SCAR 18 (2025)',
    shortName: 'ROG Strix SCAR 18',
    tier: 'high-end',
    badge: 'Best Cooling in Class',
    gpu: 'RTX 5090',
    gpuVram: '24GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 275HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '2TB PCIe Gen4 NVMe',
    display: {
      size: 18,
      res: '2560×1600',
      hz: 240,
      panel: 'Mini-LED',
      nits: 1200,
      hdr: 'HDR1000',
    },
    weight: 3.1,
    battery: 90,
    price: 4499,
    score: 9.6,
    scores: { perf: 9.8, display: 9.0, thermals: 9.5, battery: 6.8, build: 9.6, value: 8.2 },
    bestFor: 'Sustained max performance, competitive gaming',
    avoidIf: 'Battery life or portability matter',
    amazonUrl: 'https://www.amazon.com/dp/B0DW1WX8H2?tag=framelimit20-20',
    amazonAsin: 'B0DW1WX8H2',
    imgUrl: 'images/laptops/asus-rog-strix-scar-18.webp',
    imgBg: '#0d0d14',
    tags: ['desktop-replacement', 'nvidia', 'amd-cpu', 'cooling-king', 'flagship'],
  },

  {
    id: 'asus-rog-scar-16-2026',
    brand: 'ASUS ROG',
    name: 'Strix SCAR 16 (2025)',
    shortName: 'ROG Strix SCAR 16',
    tier: 'high-end',
    badge: 'Best 16" Performance',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 275HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '2TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'Mini-LED',
      nits: 1200,
      hdr: 'HDR1000',
    },
    weight: 2.7,
    battery: 90,
    price: 3799,
    score: 9.4,
    scores: { perf: 9.6, display: 9.0, thermals: 9.3, battery: 7.2, build: 9.5, value: 8.6 },
    bestFor: 'Portable flagship, competitive esports + AAA',
    avoidIf: 'You need OLED or a lighter chassis',
    amazonUrl: 'https://www.amazon.com/dp/B0DW1SB1F9?tag=framelimit20-20',
    amazonAsin: 'B0DW1SB1F9',
    imgUrl: 'images/laptops/asus-rog-strix-scar-16.webp',
    imgBg: '#0d0d14',
    tags: ['16-inch', 'nvidia', 'amd-cpu', 'cooling-king', 'flagship'],
  },

  {
    id: 'lenovo-legion-pro-7i-gen10',
    brand: 'Lenovo',
    name: 'Legion Pro 7i Gen 10',
    shortName: 'Legion Pro 7i Gen 10',
    tier: 'high-end',
    badge: 'Best Value Flagship',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 275HX',
    ram: '32GB DDR5-6400',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen5 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'OLED',
      nits: 500,
      hdr: 'HDR400',
    },
    weight: 2.71,
    battery: 99.9,
    price: null,
    score: 9.4,
    scores: { perf: 9.5, display: 9.8, thermals: 9.0, battery: 7.5, build: 9.2, value: 9.2 },
    bestFor: 'Max performance at the best price-per-frame with OLED display',
    avoidIf: 'You need long battery life or want AMD CPU',
    amazonUrl: 'https://www.amazon.com/dp/B0FL4HLJ56?tag=framelimit20-20',
    amazonAsin: 'B0FL4HLJ56',
    modelCode: '16IAX10H / 83F50053US',
    specSource: 'https://www.lenovo.com/us/en/p/laptops/legion-laptops/legion-pro-series/legion-pro-7i-gen-10-16-inch-intel/83f50053us',
    specCheckedAt: '2026-07-14',
    imgUrl: 'images/laptops/lenovo-legion-pro-7i-gen10.webp',
    imgBg: '#070d12',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'flagship', 'best-value-flagship'],
  },

  {
    id: 'alienware-18-area-51',
    brand: 'Alienware',
    name: '18 Area-51',
    shortName: 'Alienware 18 Area-51',
    tier: 'high-end',
    badge: 'Most Powerful Laptop Ever Made',
    gpu: 'RTX 5090',
    gpuVram: '24GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 285HX',
    ram: '64GB DDR5-5600',
    ramUpgradeable: true,
    storage: '4TB PCIe Gen5 NVMe (RAID)',
    display: {
      size: 18,
      res: '2560×1600',
      hz: 480,
      panel: 'IPS',
      nits: 500,
      hdr: 'HDR400',
    },
    weight: 4.2,
    battery: 99,
    price: 3707,
    score: 9.2,
    scores: { perf: 9.9, display: 9.2, thermals: 8.5, battery: 5.5, build: 9.8, value: 7.0 },
    bestFor: 'Absolute maximum performance, Alienware ecosystem',
    avoidIf: 'Budget exists, weight/portability matter at all',
    amazonUrl: 'https://www.amazon.com/dp/B0F5WVJBC2/?tag=framelimit20-20',
    amazonAsin: 'B0F5WVJBC2',
    imgUrl: 'images/laptops/alienware-18-area-51.webp',
    imgBg: '#07070f',
    tags: ['desktop-replacement', 'nvidia', 'flagship', '480hz'],
  },

  {
    id: 'razer-blade-16-oled-2026',
    brand: 'Razer',
    name: 'Blade 16 (2026, RZ09-0581)',
    shortName: 'Razer Blade 16 2026',
    tier: 'high-end',
    badge: 'New 2026 Review',
    status: 'evidence-review',
    gpu: 'RTX 5090',
    gpuVram: '24GB GDDR7',
    tgp: 165,
    cpu: 'Intel Core Ultra 9 386H',
    ram: '64GB LPDDR5X-9600',
    ramUpgradeable: false,
    storage: '2TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'OLED',
      nits: 1100,
      hdr: 'HDR True Black 1000',
    },
    weight: 2.14,
    battery: 90,
    price: null,
    score: null,
    scores: null,
    bestFor: 'A thin premium chassis with a 240Hz OLED and up to RTX 5090 graphics',
    avoidIf: 'You need verified independent benchmarks, upgradeable RAM, or strong value',
    amazonUrl: 'https://www.amazon.com/dp/B0H31WLMW8?tag=framelimit20-20',
    amazonAsin: 'B0H31WLMW8',
    modelCode: 'RZ09-05819EN9-R3U1',
    specSource: 'https://www.razer.com/gaming-laptops/razer-blade-16/RZ09-05819EN9-R3U1',
    specCheckedAt: '2026-07-14',
    imgUrl: 'images/laptops/razer-blade-16-oled.webp',
    imgBg: '#060606',
    tags: ['16-inch', 'nvidia', 'oled', 'thin', 'flagship', 'premium-build'],
  },

  {
    id: 'razer-blade-18-2026',
    brand: 'Razer',
    name: 'Blade 18 (2026)',
    shortName: 'Razer Blade 18',
    tier: 'high-end',
    badge: 'Best Premium 18"',
    gpu: 'RTX 5090',
    gpuVram: '24GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 290HX',
    ram: '64GB DDR5-6400',
    ramUpgradeable: true,
    storage: '2TB PCIe Gen4 NVMe',
    display: {
      size: 18,
      res: '3840×2400 / 1920×1200',
      hz: 240,
      panel: 'IPS',
      nits: 600,
      hdr: 'Dual-mode UHD+ 240Hz / FHD+ 440Hz',
    },
    weight: 3.21,
    battery: 99,
    price: 5599,
    score: 9.1,
    scores: { perf: 9.7, display: 9.0, thermals: 8.4, battery: 6.2, build: 9.9, value: 7.5 },
    bestFor: 'Razer loyalists, premium large-screen experience',
    avoidIf: 'Better value exists at same price elsewhere',
    amazonUrl: 'https://www.amazon.com/dp/B0H31VJCL8?tag=framelimit20-20',
    amazonAsin: 'B0H31VJCL8',
    modelCode: 'RZ09-0582DER9-R3U1',
    specSource: 'https://www.razer.com/gaming-laptops/razer-blade-18',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/razer-blade-18.webp',
    imgBg: '#060606',
    tags: ['desktop-replacement', 'nvidia', 'flagship', 'premium-build'],
  },

  {
    id: 'hp-omen-max-16-2026',
    brand: 'HP',
    name: 'Omen Max 16 (RTX 5080)',
    shortName: 'HP Omen Max 16',
    tier: 'high-end',
    badge: 'Best Underrated Flagship',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 275HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '1TB PCIe NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'IPS',
      nits: 500,
      hdr: 'HDR400',
    },
    weight: 2.9,
    battery: 83,
    price: 2998,
    score: 9.1,
    scores: { perf: 9.4, display: 8.8, thermals: 8.8, battery: 7.6, build: 9.0, value: 9.3 },
    bestFor: 'Full-power RTX 5080 performance with upgradeable memory',
    avoidIf: 'You prefer OLED or need more than 1TB from the factory',
    amazonUrl: 'https://www.amazon.com/dp/B0F17BHVV1?tag=framelimit20-20',
    amazonAsin: 'B0F17BHVV1',
    modelCode: 'B64BNUA#ABA',
    specSource: 'https://www.hp.com/us-en/shop/pdp/omen-max-gaming-laptop-16t-ah000-16-b64bnua-aba-1',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/hp-omen-max-16.webp',
    imgBg: '#0a0a0a',
    tags: ['16-inch', 'nvidia', 'flagship', 'best-value-flagship'],
  },

  {
    id: 'asus-rog-zephyrus-g16-high',
    brand: 'ASUS ROG',
    name: 'Zephyrus G16 (2025, RTX 5080)',
    shortName: 'Zephyrus G16 High-End',
    tier: 'high-end',
    badge: 'Thinnest Flagship',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 150,
    cpu: 'Intel Core Ultra 9 285H',
    ram: '32GB LPDDR5X',
    ramUpgradeable: false,
    storage: '2TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'OLED',
      nits: 1100,
      hdr: 'HDR True Black 600',
    },
    weight: 1.85,
    battery: 90,
    price: 3939,
    score: 9.2,
    scores: { perf: 9.1, display: 9.8, thermals: 8.5, battery: 8.2, build: 9.6, value: 8.4 },
    bestFor: 'Portable flagship, best OLED + performance balance',
    avoidIf: 'You need full 175W TGP or upgradeable RAM',
    amazonUrl: 'https://www.amazon.com/dp/B0FLM687GK?tag=framelimit20-20',
    amazonAsin: 'B0FLM687GK',
    imgUrl: 'images/laptops/asus-rog-zephyrus-g16.webp',
    imgBg: '#080d12',
    tags: ['16-inch', 'nvidia', 'oled', 'thin', 'flagship'],
  },

  /* ============================================================
     ⚖️ MID-RANGE — RTX 5070 / 5070 Ti  (YOUR MONEY MAKERS)
     ============================================================ */
  {
    id: 'lenovo-legion-5i-gen10',
    brand: 'Lenovo',
    name: 'Legion 5i Gen 10',
    shortName: 'Lenovo Legion 5i',
    tier: 'mid-range',
    badge: '#1 Mid-Range Pick',
    gpu: 'RTX 5070',
    gpuVram: '8GB GDDR7',
    tgp: 115,
    cpu: 'Intel Core Ultra 7 255HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '1TB PCIe NVMe',
    display: {
      size: 15.1,
      res: '2560×1600',
      hz: 165,
      panel: 'OLED',
      nits: 500,
      hdr: 'HDR True Black',
    },
    weight: 1.9,
    battery: 80,
    price: 1899,
    score: 9.2,
    scores: { perf: 9.1, display: 8.5, thermals: 9.0, battery: 7.8, build: 8.8, value: 9.5 },
    bestFor: 'High-performance 1440p gaming with a 165Hz OLED display',
    avoidIf: 'You need more than 8GB VRAM or dislike glossy OLED panels',
    amazonUrl: 'https://www.amazon.com/dp/B0FSY77WS1?tag=framelimit20-20',
    amazonAsin: 'B0FSY77WS1',
    modelCode: '15IAX10 / 83N20003BO',
    specSource: 'https://www.lenovo.com/br/pt/p/laptops/legion-laptops/legion-5-series/lenovo-legion-5i-gen-10-15-inch-intel/83n20003bo/',
    specCheckedAt: '2026-07-14',
    imgUrl: 'images/laptops/lenovo-legion-5i.webp',
    imgBg: '#070d12',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'best-value', 'mid-range'],
  },

  {
    id: 'lenovo-legion-5-gen10-amd',
    brand: 'Lenovo',
    name: 'Legion 5 Gen 10 (AMD, RTX 5060)',
    shortName: 'Lenovo Legion 5 AMD',
    tier: 'mid-range',
    badge: 'Best AMD Mid-Range',
    status: 'evidence-review',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 115,
    cpu: 'AMD Ryzen 7 260',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 15.1,
      res: '2560×1600',
      hz: 165,
      panel: 'OLED',
      nits: 500,
      hdr: 'DisplayHDR True Black 600',
    },
    weight: 2.0,
    battery: 80,
    price: 1299,
    score: null,
    scores: null,
    bestFor: 'AMD-platform buyers who want RTX 5060 and a 15.1-inch OLED',
    avoidIf: 'You need more than 8GB VRAM or a higher-power GPU tier',
    amazonUrl: 'https://www.amazon.com/dp/B0FPFP4T1R?tag=framelimit20-20',
    amazonAsin: 'B0FPFP4T1R',
    modelCode: 'Legion 5 15AHP10 retail configuration',
    specSource: 'https://psref.lenovo.com/Product/Legion/Legion_5_15AHP10',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/lenovo-legion-5-amd.webp',
    imgBg: '#070d12',
    tags: ['16-inch', 'nvidia', 'amd-cpu', 'best-value', 'mid-range'],
  },

  {
    id: 'razer-blade-14-2025',
    brand: 'Razer',
    name: 'Blade 14 (2025, RTX 5070)',
    shortName: 'Razer Blade 14',
    tier: 'mid-range',
    badge: 'Compact OLED Alternative',
    status: 'evidence-review',
    gpu: 'RTX 5070',
    gpuVram: '8GB GDDR7',
    tgp: 115,
    cpu: 'AMD Ryzen AI 9 365',
    ram: '32GB LPDDR5X',
    ramUpgradeable: false,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 14,
      res: '2880×1800',
      hz: 120,
      panel: 'OLED',
      nits: 400,
      hdr: 'HDR',
    },
    weight: 1.63,
    battery: 72,
    price: 2499,
    score: null,
    scores: null,
    bestFor: 'Compact OLED gaming with exact native-performance evidence',
    avoidIf: 'You need upgradeable memory or more than 8GB VRAM',
    amazonUrl: 'https://www.amazon.com/dp/B0DYLB2QRF?tag=framelimit20-20',
    amazonAsin: 'B0DYLB2QRF',
    modelCode: 'RZ09-05306ES3-R3U1',
    specSource: 'https://mysupport.razer.com/app/answers/detail/a_id/15088',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/razer-blade-14-2026.webp',
    imgBg: '#080b0d',
    tags: ['14-inch', 'nvidia', 'amd-cpu', 'oled', 'thin', 'mid-range', 'evidence-review'],
  },

  {
    id: 'asus-rog-zephyrus-g14-2026',
    brand: 'ASUS ROG',
    name: 'Zephyrus G14 (2025, RTX 5070)',
    shortName: 'Zephyrus G14',
    tier: 'mid-range',
    badge: 'Best Compact Powerhouse',
    gpu: 'RTX 5070',
    gpuVram: '8GB GDDR7',
    tgp: 110,
    cpu: 'AMD Ryzen 9 270',
    ram: '32GB LPDDR5X',
    ramUpgradeable: false,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 14,
      res: '2880×1800',
      hz: 120,
      panel: 'OLED',
      nits: 1100,
      hdr: 'HDR True Black 600',
    },
    weight: 1.57,
    battery: 73,
    price: 2299,
    score: 9.0,
    scores: { perf: 8.6, display: 9.8, thermals: 8.2, battery: 8.6, build: 9.5, value: 8.8 },
    bestFor: 'Ultraportable + OLED, travel-friendly gamer',
    avoidIf: 'You need max FPS or upgradeable RAM',
    amazonUrl: 'https://www.amazon.com/dp/B0FHZNH1MW?tag=framelimit20-20',
    amazonAsin: 'B0FHZNH1MW',
    modelCode: 'GA403UP-CS96',
    specSource: 'https://rog.asus.com/us/laptops/rog-zephyrus/rog-zephyrus-g14-2025/',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/asus-rog-zephyrus-g14.webp',
    imgBg: '#0d0d14',
    tags: ['14-inch', 'nvidia', 'intel-cpu', 'oled', 'thin', 'mid-range'],
  },

  {
    id: 'asus-rog-zephyrus-g16-mid',
    brand: 'ASUS ROG',
    name: 'Zephyrus G16 (RTX 5070 Ti)',
    shortName: 'Zephyrus G16 Mid',
    tier: 'mid-range',
    badge: 'Best OLED Under $2K',
    gpu: 'RTX 5070 Ti',
    gpuVram: '12GB GDDR7',
    tgp: null,
    cpu: 'Intel Core Ultra 9 285H',
    ram: '32GB LPDDR5X',
    ramUpgradeable: false,
    storage: '2TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'OLED',
      nits: 1100,
      hdr: 'HDR True Black 600',
    },
    weight: 1.85,
    battery: 90,
    price: 3399,
    score: 8.9,
    scores: { perf: 8.8, display: 9.8, thermals: 8.3, battery: 8.0, build: 9.6, value: 8.6 },
    bestFor: 'OLED quality + portability at mid-range money',
    avoidIf: 'Max TGP or upgradeable RAM is required',
    amazonUrl: 'https://www.amazon.com/dp/B0FGRTF913?tag=framelimit20-20',
    amazonAsin: 'B0FGRTF913',
    modelCode: 'GU605CR retail configuration',
    specSource: 'https://rog.asus.com/us/laptops/rog-zephyrus/rog-zephyrus-g16-2025/',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/asus-rog-zephyrus-g16.webp',
    imgBg: '#080d12',
    tags: ['16-inch', 'nvidia', 'oled', 'thin', 'mid-range'],
  },

  {
    id: 'acer-predator-helios-neo-16-2025',
    brand: 'Acer',
    name: 'Predator Helios Neo 16 AI',
    shortName: 'Predator Helios Neo 16',
    tier: 'mid-range',
    badge: 'Best Budget Mid-Range',
    gpu: 'RTX 5070 Ti',
    gpuVram: '12GB GDDR7',
    tgp: 115,
    cpu: 'Intel Core Ultra 9 275HX',
    ram: '32GB DDR5',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 165,
      panel: 'OLED',
      nits: null,
      hdr: false,
    },
    weight: 2.3,
    battery: 76,
    price: 1849,
    score: 8.7,
    scores: { perf: 8.8, display: 8.4, thermals: 8.6, battery: 7.4, build: 8.5, value: 9.3 },
    bestFor: 'High-performance gaming on a strict budget',
    avoidIf: 'You need a full-power RTX 5070 Ti implementation',
    amazonUrl: 'https://www.amazon.com/dp/B0G5XC26P7/?tag=framelimit20-20',
    amazonAsin: 'B0G5XC26P7',
    modelCode: 'PHN16S-71-98RF / NH.QZQAA.001',
    specSource: 'https://www.acer.com/us-en/predator/laptops/helios/helios-neo-16s-ai/pdp/NH.QZQAA.001',
    specCheckedAt: '2026-07-14',
    imgUrl: 'images/laptops/acer-predator-helios-neo-16.webp',
    imgBg: '#05100a',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'mid-range', 'best-value'],
  },

  {
    id: 'hp-omen-16-rtx5070-2026',
    brand: 'HP',
    name: 'Omen 16 Slim 16-an0000 (RTX 5070)',
    shortName: 'HP Omen 16 Slim',
    tier: 'mid-range',
    badge: 'Configurable RTX 5070',
    gpu: 'RTX 5070',
    gpuVram: '8GB GDDR7',
    tgp: null,
    cpu: 'Intel Core Ultra 7 255H',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 144,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.4,
    battery: 70,
    price: 1669,
    score: 8.5,
    scores: { perf: 8.6, display: 7.8, thermals: 8.4, battery: 8.0, build: 8.6, value: 9.0 },
    bestFor: 'Upgradeable RTX 5070 system with several display options',
    avoidIf: 'The retailer does not identify the exact 16-an0000 configuration',
    amazonUrl: 'https://www.amazon.com/dp/B0G31VXF5L?tag=framelimit20-20',
    amazonAsin: 'B0G31VXF5L',
    specCheckedAt: '2026-07-15',
    modelCode: '16-an0000',
    specSource: 'https://support.hp.com/us-en/document/ish_12515572-12516081-16',
    specCheckedAt: '2026-07-14',
    imgUrl: 'images/laptops/hp-omen-16-rtx5070.webp',
    imgBg: '#0a0a0a',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'mid-range'],
  },

  {
    id: 'asus-tuf-gaming-f16-rtx5070',
    brand: 'ASUS TUF',
    name: 'Gaming F16 (RTX 5070)',
    shortName: 'TUF Gaming F16',
    tier: 'mid-range',
    badge: 'Best Mid-Range Build Quality',
    gpu: 'RTX 5070',
    gpuVram: '8GB GDDR7',
    tgp: 115,
    cpu: 'Intel Core i7-14650HX',
    ram: '32GB DDR5',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 165,
      panel: 'IPS',
      nits: null,
      hdr: false,
    },
    weight: 2.2,
    battery: 90,
    price: 1969,
    score: 8.6,
    scores: { perf: 8.5, display: 8.3, thermals: 8.8, battery: 8.4, build: 9.2, value: 9.2 },
    bestFor: 'MIL-SPEC durability, 32GB RAM, and a 165Hz G-SYNC display',
    avoidIf: 'You need maximum GPU TGP',
    amazonUrl: 'https://www.amazon.com/dp/B0G6Y8YTX7?tag=framelimit20-20',
    amazonAsin: 'B0G6Y8YTX7',
    modelCode: 'FX507 retail configuration',
    specSource: 'https://www.asus.com/us/laptops/for-gaming/tuf-gaming/asus-tuf-gaming-f16-2024/techspec/',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/asus-tuf-gaming-f16.webp',
    imgBg: '#0a0d0a',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'mid-range', 'best-value'],
  },

  {
    id: 'asus-tuf-gaming-a16-amd',
    brand: 'ASUS TUF',
    name: 'Gaming A16 (2025, RTX 5070)',
    shortName: 'TUF Gaming A16 RTX 5070',
    tier: 'mid-range',
    badge: 'Current AMD Platform SKU',
    status: 'evidence-review',
    gpu: 'RTX 5070',
    gpuVram: '8GB GDDR7',
    tgp: 115,
    cpu: 'AMD Ryzen 9 270',
    ram: '32GB DDR5',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 165,
      panel: 'IPS',
      nits: null,
      hdr: false,
    },
    weight: 2.2,
    battery: 90,
    price: 1799,
    score: null,
    scores: null,
    bestFor: 'A current AMD CPU platform with RTX 5070 graphics and upgradeable memory',
    avoidIf: 'You need an OLED panel or a factory-sealed memory configuration',
    amazonUrl: 'https://www.amazon.com/dp/B0GGXQ45H3?tag=framelimit20-20',
    amazonAsin: 'B0GGXQ45H3',
    modelCode: 'TUF A16 retail 32GB configuration',
    specSource: 'https://www.asus.com/us/laptops/for-gaming/tuf-gaming/asus-tuf-gaming-a16-2025/techspec/',
    specCheckedAt: '2026-07-16',
    imgUrl: 'images/laptops/asus-tuf-gaming-a16-amd-advantage.webp',
    imgBg: '#0a0d0a',
    tags: ['16-inch', 'nvidia', 'amd-cpu', 'mid-range', 'evidence-review'],
  },

  {
    id: 'msi-vector-16-hx-ai',
    brand: 'MSI',
    name: 'Vector 16 HX AI',
    shortName: 'MSI Vector 16 HX AI',
    tier: 'mid-range',
    badge: 'Best MSI Mid-Range',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 275HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '2TB NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'IPS',
      nits: 500,
      hdr: 'HDR400',
    },
    weight: 2.7,
    battery: 90,
    price: null,
    score: 9.0,
    scores: { perf: 9.0, display: 8.8, thermals: 8.7, battery: 7.6, build: 8.9, value: 8.9 },
    bestFor: 'Near-flagship performance at mid-range price',
    avoidIf: 'OLED display or thin chassis is a priority',
    amazonUrl: 'https://www.amazon.com/dp/B0DTN19VXZ/?tag=framelimit20-20',
    amazonAsin: 'B0DTN19VXZ',
    modelCode: 'A2XWIG-058US',
    specSource: 'https://us.msi.com/Laptop/Vector-16-HX-AI-A2XWX/Specification',
    specCheckedAt: '2026-07-14',
    imgUrl: 'images/laptops/msi-vector-16-hx-ai.webp',
    imgBg: '#0d0d0d',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'mid-range'],
  },

  {
    id: 'dell-alienware-16x-aurora',
    brand: 'Alienware',
    name: '16X Aurora (RTX 5070)',
    shortName: 'Alienware 16X Aurora',
    tier: 'mid-range',
    badge: 'Best Alienware Mid-Range',
    gpu: 'RTX 5070',
    gpuVram: '8GB GDDR7',
    tgp: 115,
    cpu: 'Intel Core Ultra 9 275HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '2TB NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 240,
      panel: 'IPS',
      nits: 400,
      hdr: false,
    },
    weight: 2.57,
    battery: 90,
    price: 2447,
    score: 8.7,
    scores: { perf: 9.0, display: 8.5, thermals: 8.8, battery: 7.2, build: 9.4, value: 8.4 },
    bestFor: 'Alienware build quality at a non-Alienware price',
    avoidIf: 'Better value exists from Legion/SCAR at same price',
    amazonUrl: 'https://www.amazon.com/dp/B0FWCQ2B6J/?tag=framelimit20-20',
    amazonAsin: 'B0FWCQ2B6J',
    imgUrl: 'images/laptops/alienware-16x-aurora-m16.webp',
    imgBg: '#07070f',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'mid-range'],
  },

  /* ============================================================
     💰 BUDGET — RTX 5050 / 5060 (NEW GEN ONLY)
     ============================================================ */
  {
    id: 'lenovo-loq-15-gen10',
    brand: 'Lenovo',
    name: 'LOQ 15 Gen 10 (RTX 5060)',
    shortName: 'Lenovo LOQ 15',
    tier: 'budget',
    badge: '#1 Budget Pick',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 115,
    cpu: 'AMD Ryzen 7 250',
    ram: '16GB DDR5-5600',
    ramUpgradeable: true,
    storage: '512GB PCIe Gen4 NVMe',
    display: {
      size: 15.6,
      res: '1920×1080',
      hz: 144,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.3,
    battery: 60,
    price: 1329,
    score: 8.5,
    scores: { perf: 8.0, display: 7.8, thermals: 8.6, battery: 7.2, build: 8.4, value: 9.6 },
    bestFor: 'Best-value RTX 5060 pick for 1080p gaming',
    avoidIf: '1440p or OLED is something you care about',
    amazonUrl: 'https://www.amazon.com/dp/B0G2LHS38J?tag=framelimit20-20',
    amazonAsin: 'B0G2LHS38J',
    specCheckedAt: '2026-07-15',
    modelCode: '15AHP10',
    specSource: 'https://psref.lenovo.com/syspool/Sys/PDF/LOQ/LOQ_15AHP10/LOQ_15AHP10_Spec.pdf',
    specCheckedAt: '2026-07-14',
    imgUrl: 'images/laptops/lenovo-loq-15-gen10.webp',
    imgBg: '#070d12',
    tags: ['15-inch', 'nvidia', 'amd-cpu', 'budget', 'best-value'],
  },

  {
    id: 'acer-nitro-16-2025',
    brand: 'Acer',
    name: 'Nitro 16S AI (2025)',
    shortName: 'Acer Nitro 16S AI',
    tier: 'budget',
    badge: 'Best Acer Budget Pick',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 115,
    cpu: 'AMD Ryzen AI 7 350',
    ram: '16GB DDR5',
    ramUpgradeable: true,
    storage: '1TB PCIe NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 180,
      panel: 'IPS',
      nits: null,
      hdr: false,
    },
    weight: 2.18,
    battery: 76,
    price: null,
    score: 8.3,
    scores: { perf: 8.1, display: 8.0, thermals: 8.2, battery: 7.6, build: 8.2, value: 8.8 },
    bestFor: 'A 115W RTX 5060 and 180Hz 16:10 display in a slim 16-inch chassis',
    avoidIf: 'You want a QHD display or confirmed live pricing',
    amazonUrl: 'https://www.amazon.com/dp/B0FS861DH8?tag=framelimit20-20',
    amazonAsin: 'B0FS861DH8',
    specCheckedAt: '2026-07-15',
    modelCode: 'AN16S-61-R7YL / NH.U19AA.001',
    specSource: 'https://www.acer.com/us-en/laptops/nitro/nitro-v-16s-ai-amd/pdp/NH.U19AA.001',
    specCheckedAt: '2026-07-14',
    imgUrl: 'images/laptops/acer-nitro-16.webp',
    imgBg: '#05100a',
    tags: ['16-inch', 'nvidia', 'amd-cpu', 'budget'],
  },

  {
    id: 'acer-nitro-v-16',
    brand: 'Acer',
    name: 'Nitro V 16S AI (2025)',
    shortName: 'Acer Nitro V 16S AI',
    tier: 'budget',
    badge: 'Best 32GB Budget Option',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 85,
    cpu: 'AMD Ryzen 7 260',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 180,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.1,
    battery: 76,
    price: null,
    score: 8.1,
    scores: { perf: 7.8, display: 7.6, thermals: 7.8, battery: 6.8, build: 7.2, value: 8.8 },
    bestFor: '32GB memory and a 180Hz display in a budget RTX 5060 configuration',
    avoidIf: 'You want a higher-power RTX 5060 or premium build quality',
    amazonUrl: 'https://www.amazon.com/dp/B0F195W823?tag=framelimit20-20',
    amazonAsin: 'B0F195W823',
    specCheckedAt: '2026-07-15',
    modelCode: 'ANV16S-41-R2AJ / NH.QZYAA.001',
    specSource: 'https://www.acer.com/us-en/laptops/nitro/nitro-v-16s-ai-amd/pdp/NH.QZYAA.001',
    specCheckedAt: '2026-07-14',
    imgUrl: 'images/laptops/acer-nitro-v-16.webp',
    imgBg: '#05100a',
    tags: ['16-inch', 'nvidia', 'amd-cpu', 'budget'],
  },

  {
    id: 'asus-tuf-a16-entry',
    brand: 'ASUS TUF',
    name: 'Gaming A16 (64GB, RTX 5070)',
    shortName: 'TUF Gaming A16 64GB',
    tier: 'mid-range',
    badge: 'High-Memory TUF Pick',
    gpu: 'RTX 5070',
    gpuVram: '8GB GDDR7',
    tgp: 115,
    cpu: 'AMD Ryzen 9 270',
    ram: '64GB DDR5',
    ramUpgradeable: true,
    storage: '1TB PCIe NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 165,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.2,
    battery: 90,
    price: 2099,
    score: 8.4,
    scores: { perf: 8.0, display: 8.2, thermals: 8.8, battery: 8.8, build: 9.2, value: 9.0 },
    bestFor: 'Heavy multitasking, content creation, and RTX 5070 gaming',
    avoidIf: 'You only need 16GB or 32GB and want the lowest price',
    amazonUrl: 'https://www.amazon.com/dp/B0G3XTVGTD?tag=framelimit20-20',
    amazonAsin: 'B0G3XTVGTD',
    modelCode: 'FA608 retail 64GB configuration',
    specSource: 'https://www.asus.com/us/laptops/for-gaming/tuf-gaming/asus-tuf-gaming-a16-2025/techspec/',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/asus-tuf-gaming-a16-amd-advantage.webp',
    imgBg: '#0a0d0a',
    tags: ['16-inch', 'nvidia', 'amd-cpu', 'budget'],
  },

  {
    id: 'msi-katana-15-hx',
    brand: 'MSI',
    name: 'Katana 15 HX (RTX 5070)',
    shortName: 'MSI Katana 15 HX',
    tier: 'budget',
    badge: 'Best MSI Budget Pick',
    gpu: 'RTX 5070',
    gpuVram: '8GB GDDR7',
    tgp: 115,
    cpu: 'Intel Core i9-14900HX',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 15.6,
      res: '2560×1440',
      hz: 165,
      panel: 'IPS',
      nits: 250,
      hdr: false,
    },
    weight: 2.4,
    battery: 75,
    price: 1744,
    score: 7.9,
    scores: { perf: 7.8, display: 7.4, thermals: 8.0, battery: 6.8, build: 8.2, value: 9.0 },
    bestFor: 'RTX 5070 performance and QHD gaming in a 15-inch chassis',
    avoidIf: 'Battery life or display brightness matters',
    amazonUrl: 'https://www.amazon.com/dp/B0DZFVBQLK/?tag=framelimit20-20',
    amazonAsin: 'B0DZFVBQLK',
    modelCode: 'Katana 15 HX B14WGK',
    specSource: 'https://www.msi.com/Laptop/Katana-15-HX-B14WX/Specification',
    specCheckedAt: '2026-07-14',
    imgUrl: 'images/laptops/msi-katana-15-hx.webp',
    imgBg: '#0a0a0a',
    tags: ['15-inch', 'nvidia', 'intel-cpu', 'budget'],
  },

  {
    id: 'gigabyte-gaming-a16-rtx5060',
    brand: 'Gigabyte',
    name: 'Gaming A16 (RTX 5060)',
    shortName: 'Gigabyte Gaming A16',
    tier: 'budget',
    badge: 'Best Hidden Gem',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 85,
    cpu: 'Intel Core i7-13620H',
    ram: '16GB DDR5-5200',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: {
      size: 16,
      res: '1920×1200',
      hz: 165,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.2,
    battery: 76,
    price: 1337,
    score: 7.8,
    scores: { perf: 7.8, display: 7.9, thermals: 8.0, battery: 6.5, build: 7.8, value: 9.2 },
    bestFor: 'Underrated budget pick, good display ratio',
    avoidIf: 'Battery life is non-negotiable',
    amazonUrl: 'https://www.amazon.com/dp/B0FDMN25CZ/?tag=framelimit20-20',
    amazonAsin: 'B0FDMN25CZ',
    modelCode: 'GAMING A16 CVHI3US894SH',
    specSource: 'https://www.gigabyte.com/us/Laptop/GIGABYTE-GAMING-A16-GA6H/sp',
    specCheckedAt: '2026-07-14',
    imgUrl: 'images/laptops/gigabyte-gaming-a16.webp',
    imgBg: '#0d1117',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'budget'],
  },

  {
    id: 'dell-g16-rtx4070',
    brand: 'Alienware',
    name: '16 Aurora (RTX 5060)',
    shortName: 'Alienware 16 Aurora',
    tier: 'mid-range',
    badge: 'Current Dell Gaming Pick',
    gpu: 'RTX 5060',
    gpuVram: '8GB GDDR7',
    tgp: 115,
    cpu: 'Intel Core 7 240H',
    ram: '32GB DDR5-5600',
    ramUpgradeable: true,
    storage: '1TB PCIe NVMe',
    display: {
      size: 16,
      res: '2560×1600',
      hz: 120,
      panel: 'IPS',
      nits: 300,
      hdr: false,
    },
    weight: 2.57,
    battery: 60,
    price: 1699,
    score: 8.4,
    scores: { perf: 7.8, display: 8.8, thermals: 8.2, battery: 7.4, build: 8.4, value: 9.0 },
    bestFor: 'A current Dell gaming laptop with a sharp 16-inch display and 32GB RAM',
    avoidIf: 'You want a faster 165Hz or 240Hz panel',
    amazonUrl: 'https://www.amazon.com/dp/B0FXX3QS1F?tag=framelimit20-20',
    amazonAsin: 'B0FXX3QS1F',
    modelCode: 'Alienware 16 Aurora AC16250',
    specSource: 'https://www.dell.com/en-us/shop/dell-laptops/alienware-16-aurora-gaming-laptop/spd/alienware-aurora-ac16250-gaming-laptop',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/alienware-16x-aurora-m16.webp',
    imgBg: '#0d1117',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'mid-range'],
  },

  {
    id: 'asus-rog-zephyrus-g16-2026',
    brand: 'ASUS ROG',
    name: 'Zephyrus G16 (2025, RTX 5080 32GB)',
    shortName: 'Zephyrus G16 RTX 5080',
    tier: 'high-end',
    badge: 'New 2026 Review',
    status: 'evidence-review',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 120,
    cpu: 'Intel Core Ultra 9 285H',
    ram: '32GB LPDDR5X',
    ramUpgradeable: false,
    storage: '2TB PCIe Gen4 NVMe',
    display: { size: 16, res: '2560×1600', hz: 240, panel: 'OLED', nits: 500, hdr: 'HDR True Black 500' },
    weight: 1.85,
    battery: 90,
    price: 3699,
    score: null,
    scores: null,
    bestFor: 'Portable flagship buyers who want a 240Hz OLED and high-end creator performance',
    avoidIf: 'You need upgradeable memory or full 175W GPU power',
    amazonUrl: 'https://www.amazon.com/dp/B0DYZ8BSQY?tag=framelimit20-20',
    amazonAsin: 'B0DYZ8BSQY',
    modelCode: 'GU605CW-G16.U95080-HID1',
    specSource: 'https://rog.asus.com/us/laptops/rog-zephyrus/rog-zephyrus-g16-2025/spec/',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/asus-rog-zephyrus-g16.webp',
    imgBg: '#080d12',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'oled', 'thin', 'flagship', 'evidence-review'],
  },

  {
    id: 'msi-raider-16-max-hx',
    brand: 'MSI',
    name: 'Raider 18 HX AI (64GB, RTX 5090)',
    shortName: 'MSI Raider 18 HX 64GB',
    tier: 'high-end',
    badge: 'New 2026 Review',
    status: 'evidence-review',
    gpu: 'RTX 5090',
    gpuVram: '24GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 285HX',
    ram: '64GB DDR5',
    ramUpgradeable: true,
    storage: '1TB PCIe NVMe',
    display: { size: 18, res: '3840×2400', hz: 120, panel: 'Mini LED', nits: 1000, hdr: 'VESA DisplayHDR 1000' },
    weight: 3.6,
    battery: 99.9,
    price: 4179,
    score: null,
    scores: null,
    bestFor: '4K Mini LED gaming, 64GB memory, and desktop-replacement performance',
    avoidIf: 'Portability or a compact power adapter matters',
    amazonUrl: 'https://www.amazon.com/dp/B0FXHBZCK3?tag=framelimit20-20',
    amazonAsin: 'B0FXHBZCK3',
    modelCode: 'Raider 18 HX AI A2XWJG retail 64GB configuration',
    specSource: 'https://www.msi.com/Laptop/Raider-18-HX-AI-A2XWX/Specification',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/msi-raider-18-hx-ai.webp',
    imgBg: '#07090c',
    tags: ['desktop-replacement', 'nvidia', 'intel-cpu', 'mini-led', 'flagship', 'evidence-review'],
  },

  {
    id: 'asus-rog-strix-g16-2026',
    brand: 'ASUS ROG',
    name: 'Strix G16 (2025, G615LW)',
    shortName: 'ROG Strix G16 RTX 5080',
    tier: 'high-end',
    badge: 'New 2026 Review',
    status: 'evidence-review',
    gpu: 'RTX 5080',
    gpuVram: '16GB GDDR7',
    tgp: 175,
    cpu: 'Intel Core Ultra 9 275HX',
    ram: '64GB DDR5',
    ramUpgradeable: true,
    storage: '1TB PCIe Gen4 NVMe',
    display: { size: 16, res: '2560×1600', hz: 240, panel: 'IPS', nits: 500, hdr: 'Dolby Vision' },
    weight: 2.65,
    battery: 90,
    price: 3698,
    score: null,
    scores: null,
    bestFor: 'Full-power RTX 5080 gaming with 64GB RAM and a 240Hz Nebula display',
    avoidIf: 'You want a thin laptop or Mini LED local dimming',
    amazonUrl: 'https://www.amazon.com/dp/B0FLZC7J3B?tag=framelimit20-20',
    amazonAsin: 'B0FLZC7J3B',
    modelCode: 'G615LW retail 64GB configuration',
    specSource: 'https://rog.asus.com/us/laptops/rog-strix/rog-strix-g16-2025/spec/',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/asus-rog-strix-g16-2026.webp',
    imgBg: '#080b10',
    tags: ['16-inch', 'nvidia', 'intel-cpu', 'mini-led', 'flagship', 'evidence-review'],
  },

  {
    id: 'msi-raider-a18-hx-amd',
    brand: 'MSI',
    name: 'Raider A18 HX A9WJG-052US',
    shortName: 'MSI Raider A18 HX AMD',
    tier: 'high-end',
    badge: 'AMD X3D Flagship',
    status: 'evidence-review',
    gpu: 'RTX 5090',
    gpuVram: '24GB GDDR7',
    tgp: 175,
    cpu: 'AMD Ryzen 9 9955HX3D',
    ram: '64GB DDR5-5600',
    ramUpgradeable: true,
    storage: '2TB NVMe SSD',
    display: { size: 18, res: '3840×2400', hz: 120, panel: 'Mini-LED', nits: 1000, hdr: 'VESA DisplayHDR 1000' },
    weight: 3.6,
    battery: 99.9,
    price: 4299,
    score: null,
    scores: null,
    bestFor: 'Ryzen X3D gaming performance with a full-power RTX 5090',
    avoidIf: 'You need portability or a value-focused configuration',
    amazonUrl: 'https://www.amazon.com/dp/B0DVDH7JCV?tag=framelimit20-20',
    amazonAsin: 'B0DVDH7JCV',
    modelCode: 'A9WJG-052US',
    specSource: 'https://www.msi.com/Laptop/Raider-A18-HX-A9WX/Specification',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/msi-raider-18-hx-ai.webp',
    imgBg: '#07090c',
    tags: ['desktop-replacement', 'nvidia', 'amd-cpu', 'x3d', 'mini-led', 'flagship', 'evidence-review'],
  },

  {
    id: 'asus-rog-flow-z13-radeon-8060s',
    brand: 'ASUS ROG',
    name: 'Flow Z13 (2025, GZ302EA-XS96)',
    shortName: 'ROG Flow Z13 Radeon 8060S',
    tier: 'high-end',
    badge: 'Best Radeon iGPU',
    status: 'evidence-review',
    gpu: 'Radeon 8060S',
    gpuVram: 'Shared LPDDR5X',
    tgp: null,
    cpu: 'AMD Ryzen AI MAX+ 395',
    ram: '32GB LPDDR5X-8000',
    ramUpgradeable: false,
    storage: '1TB PCIe Gen4 NVMe',
    display: { size: 13.4, res: '2560×1600', hz: 180, panel: 'IPS Touch', nits: 500, hdr: 'Dolby Vision' },
    weight: 1.59,
    battery: 70,
    price: 1999,
    score: null,
    scores: null,
    bestFor: 'Portable all-AMD gaming, creation, and high-memory iGPU workloads',
    avoidIf: 'You want a conventional clamshell or upgradeable memory',
    amazonUrl: 'https://www.amazon.com/dp/B0DT7MNLTD?tag=framelimit20-20',
    amazonAsin: 'B0DT7MNLTD',
    modelCode: 'GZ302EA-XS96',
    specSource: 'https://rog.asus.com/us/laptops/rog-flow/rog-flow-z13-2025/spec/',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/asus-rog-flow-z13-2025.webp',
    imgBg: '#07090c',
    tags: ['portable', '2-in-1', 'amd-cpu', 'amd-gpu', 'radeon', 'touchscreen', 'evidence-review'],
  },

  {
    id: 'asus-tuf-a16-radeon-rx7700s',
    brand: 'ASUS TUF',
    name: 'Gaming A16 Radeon RX 7700S',
    shortName: 'TUF A16 RX 7700S',
    tier: 'mid-range',
    badge: 'All-AMD Value',
    status: 'evidence-review',
    gpu: 'Radeon RX 7700S',
    gpuVram: '8GB GDDR6',
    tgp: null,
    cpu: 'AMD Ryzen 7 7735HS',
    ram: '16GB DDR5',
    ramUpgradeable: true,
    storage: '1TB NVMe SSD',
    display: { size: 16, res: '1920×1200', hz: 165, panel: 'IPS', nits: null, hdr: null },
    weight: null,
    battery: null,
    price: null,
    score: null,
    scores: null,
    bestFor: 'Radeon discrete graphics, FreeSync, and upgradeable all-AMD gaming',
    avoidIf: 'You need a current-generation CPU or QHD resolution',
    amazonUrl: 'https://www.amazon.com/dp/B0DQS8DW6Y?tag=framelimit20-20',
    amazonAsin: 'B0DQS8DW6Y',
    modelCode: 'Amazon retail configuration; OEM suffix not exposed',
    specSource: 'https://www.amazon.com/dp/B0DQS8DW6Y',
    specCheckedAt: '2026-07-15',
    imgUrl: 'images/laptops/asus-tuf-gaming-a16-amd-advantage.webp',
    imgBg: '#080b10',
    tags: ['16-inch', 'amd-cpu', 'amd-gpu', 'radeon', 'freesync', 'mid-range', 'evidence-review'],
  },

];

// Only products with a directly attributable, currently buyable Amazon product
// page are exposed to recommendation, comparison, and finder interfaces.
const LAPTOPS = LAPTOP_CATALOG.filter(laptop =>
  laptop.retailStatus !== 'unavailable' &&
  Boolean(laptop.amazonAsin) &&
  /amazon\.com\/dp\//.test(laptop.amazonUrl || '')
);

/* ──────────────────────────────────────────────
   HELPER FUNCTIONS  (available as globals)
   ────────────────────────────────────────────── */

/** Get a laptop by its id string */
function getLaptop(id) {
  return LAPTOPS.find(l => l.id === id) || null;
}

/** Group laptops by tier */
const LAPTOPS_BY_TIER = {
  'high-end':  LAPTOPS.filter(l => l.tier === 'high-end'),
  'mid-range': LAPTOPS.filter(l => l.tier === 'mid-range'),
  'budget':    LAPTOPS.filter(l => l.tier === 'budget'),
};

/** Filter by tag(s) */
function getLaptopsByTag(...tags) {
  return LAPTOPS.filter(l => tags.every(t => l.tags.includes(t)));
}

/** Sort helpers */
const sortByScore    = arr => [...arr].sort((a, b) => (b.score ?? -1) - (a.score ?? -1));
const sortByPrice    = arr => [...arr].sort((a, b) => (a.price || Infinity) - (b.price || Infinity));
const sortByTGP      = arr => [...arr].sort((a, b) => b.tgp - a.tgp);

function flIsDirectAmazonProduct(laptopOrUrl) {
  const url = typeof laptopOrUrl === 'string' ? laptopOrUrl : laptopOrUrl && laptopOrUrl.amazonUrl;
  return /amazon\.com\/dp\//.test(url || '');
}

function flRetailerStatus(laptop) {
  return flIsDirectAmazonProduct(laptop)
    ? 'Verified Amazon product page'
    : 'Amazon search fallback - verify model before buying';
}

/* Expose everything globally for plain HTML pages */
window.LAPTOPS         = LAPTOPS;
window.FL_DATA_LAST_CHECKED = FL_DATA_LAST_CHECKED;
window.FL_DATA_LAST_CHECKED_LABEL = FL_DATA_LAST_CHECKED_LABEL;
window.LAPTOPS_BY_TIER = LAPTOPS_BY_TIER;
window.getLaptop       = getLaptop;
window.getLaptopsByTag = getLaptopsByTag;
window.sortByScore     = sortByScore;
window.sortByPrice     = sortByPrice;
window.sortByTGP       = sortByTGP;
window.flIsDirectAmazonProduct = flIsDirectAmazonProduct;
window.flRetailerStatus = flRetailerStatus;
